# Generated by Django 4.1.12 on 2023-11-03 09:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolutionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "introduction_headline",
                    models.CharField(max_length=255, verbose_name="Headline"),
                ),
                (
                    "introduction_subheadline",
                    models.CharField(max_length=255, verbose_name="Sub-Headline"),
                ),
                (
                    "introduction_text",
                    models.TextField(
                        blank=True,
                        help_text="Text unter der Headline",
                        null=True,
                        verbose_name="Eingangstext",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "row",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "row_width",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("12", "Full"),
                                                    ("10", "Centered"),
                                                ],
                                                label="Row size",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "Column",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "column_size",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "",
                                                                                "Auto",
                                                                            ),
                                                                            (
                                                                                "12",
                                                                                "Full row",
                                                                            ),
                                                                            (
                                                                                "6",
                                                                                "Half - 1/2 column",
                                                                            ),
                                                                            (
                                                                                "4",
                                                                                "Thirds - 1/3 column",
                                                                            ),
                                                                            (
                                                                                "8",
                                                                                "Thirds - 2/3 column",
                                                                            ),
                                                                            (
                                                                                "3",
                                                                                "Quarters - 1/4 column",
                                                                            ),
                                                                            (
                                                                                "9",
                                                                                "Quarters - 3/4 column",
                                                                            ),
                                                                            (
                                                                                "2",
                                                                                "Sixths - 1/6 column",
                                                                            ),
                                                                            (
                                                                                "10",
                                                                                "Sixths - 5/6 column",
                                                                            ),
                                                                            (
                                                                                "1",
                                                                                "Twelfths - 1/12 column",
                                                                            ),
                                                                            (
                                                                                "5",
                                                                                "Twelfths - 5/12 column",
                                                                            ),
                                                                            (
                                                                                "7",
                                                                                "Twelfths - 7/12 column",
                                                                            ),
                                                                            (
                                                                                "11",
                                                                                "Twelfths - 11/12 column",
                                                                            ),
                                                                        ],
                                                                        label="Column size",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "content",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "image",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "image",
                                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                                required=True
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "caption",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=False
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "attribution",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                required=False
                                                                                            ),
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "text",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "pre_headline",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                help_text="The pre-title",
                                                                                                required=True,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "headline",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                help_text="The Title",
                                                                                                required=True,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "text",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Content Block",
                                                                                                required=True,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "link_text",
                                                                                            wagtail.blocks.CharBlock(
                                                                                                default="Read more",
                                                                                                help_text="Link Text",
                                                                                                required=True,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "page",
                                                                                            wagtail.blocks.PageChooserBlock(
                                                                                                help_text="page to link to",
                                                                                                required=True,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "url",
                                                                                            wagtail.blocks.URLBlock(
                                                                                                help_text="external URL to link to",
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                            ),
                                                                        ],
                                                                        label="Content",
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ],
                                                label="Content",
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Header Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SolutionIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "general",
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            "row_block",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "row_width",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ("12", "Full"),
                                                                ("10", "Centered"),
                                                            ],
                                                            label="Row size",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "content",
                                                        wagtail.blocks.StreamBlock(
                                                            [
                                                                (
                                                                    "Column",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "column_size",
                                                                                wagtail.blocks.ChoiceBlock(
                                                                                    choices=[
                                                                                        (
                                                                                            "",
                                                                                            "Auto",
                                                                                        ),
                                                                                        (
                                                                                            "12",
                                                                                            "Full row",
                                                                                        ),
                                                                                        (
                                                                                            "6",
                                                                                            "Half - 1/2 column",
                                                                                        ),
                                                                                        (
                                                                                            "4",
                                                                                            "Thirds - 1/3 column",
                                                                                        ),
                                                                                        (
                                                                                            "8",
                                                                                            "Thirds - 2/3 column",
                                                                                        ),
                                                                                        (
                                                                                            "3",
                                                                                            "Quarters - 1/4 column",
                                                                                        ),
                                                                                        (
                                                                                            "9",
                                                                                            "Quarters - 3/4 column",
                                                                                        ),
                                                                                        (
                                                                                            "2",
                                                                                            "Sixths - 1/6 column",
                                                                                        ),
                                                                                        (
                                                                                            "10",
                                                                                            "Sixths - 5/6 column",
                                                                                        ),
                                                                                        (
                                                                                            "1",
                                                                                            "Twelfths - 1/12 column",
                                                                                        ),
                                                                                        (
                                                                                            "5",
                                                                                            "Twelfths - 5/12 column",
                                                                                        ),
                                                                                        (
                                                                                            "7",
                                                                                            "Twelfths - 7/12 column",
                                                                                        ),
                                                                                        (
                                                                                            "11",
                                                                                            "Twelfths - 11/12 column",
                                                                                        ),
                                                                                    ],
                                                                                    label="Column size",
                                                                                    required=False,
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                )
                                                            ],
                                                            label="Content",
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "paragraph_block",
                                            wagtail.blocks.RichTextBlock(
                                                icon="pilcrow"
                                            ),
                                        ),
                                        (
                                            "image_block",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "image",
                                                        wagtail.images.blocks.ImageChooserBlock(
                                                            required=True
                                                        ),
                                                    ),
                                                    (
                                                        "caption",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "attribution",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "block_quote",
                                            wagtail.blocks.BlockQuoteBlock(),
                                        ),
                                        (
                                            "embed_block",
                                            wagtail.embeds.blocks.EmbedBlock(
                                                help_text="core.blocks.help_text_embed_block"
                                            ),
                                        ),
                                        (
                                            "button_block",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "page",
                                                        wagtail.blocks.PageChooserBlock(
                                                            help_text="page to link to",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "url",
                                                        wagtail.blocks.URLBlock(
                                                            help_text="external URL to link to",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="the text on the button",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "style",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "btn-primary",
                                                                    "Primary",
                                                                ),
                                                                (
                                                                    "btn-secondary",
                                                                    "Secondary",
                                                                ),
                                                                (
                                                                    "btn-success",
                                                                    "Success",
                                                                ),
                                                                (
                                                                    "btn-danger",
                                                                    "Danger",
                                                                ),
                                                                ("btn-info", "Info"),
                                                                ("btn-light", "Light"),
                                                                ("btn-dark", "Dark"),
                                                                (
                                                                    "btn-outline-primary",
                                                                    "Outline Primary",
                                                                ),
                                                                (
                                                                    "btn-outline-secondary",
                                                                    "Outline Secondary",
                                                                ),
                                                                (
                                                                    "btn-outline-success",
                                                                    "Outline Success",
                                                                ),
                                                                (
                                                                    "btn-outline-danger",
                                                                    "Outline Danger",
                                                                ),
                                                                (
                                                                    "btn-outline-info",
                                                                    "Outline Info",
                                                                ),
                                                                (
                                                                    "btn-outline-light",
                                                                    "Outline Light",
                                                                ),
                                                                (
                                                                    "btn-outline-dark",
                                                                    "Outline Dark",
                                                                ),
                                                            ],
                                                            label="Button style",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "size",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ("btn-sm", "Small"),
                                                                ("", "Default"),
                                                                ("btn-lg", "Large"),
                                                            ],
                                                            label="Button size",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ],
                                    use_json_field=True,
                                ),
                            ),
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "foreground_color",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "row_block",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "row_width",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "12",
                                                                                "Full",
                                                                            ),
                                                                            (
                                                                                "10",
                                                                                "Centered",
                                                                            ),
                                                                        ],
                                                                        label="Row size",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "content",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "Column",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "column_size",
                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                choices=[
                                                                                                    (
                                                                                                        "",
                                                                                                        "Auto",
                                                                                                    ),
                                                                                                    (
                                                                                                        "12",
                                                                                                        "Full row",
                                                                                                    ),
                                                                                                    (
                                                                                                        "6",
                                                                                                        "Half - 1/2 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "4",
                                                                                                        "Thirds - 1/3 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "8",
                                                                                                        "Thirds - 2/3 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "3",
                                                                                                        "Quarters - 1/4 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "9",
                                                                                                        "Quarters - 3/4 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "2",
                                                                                                        "Sixths - 1/6 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "10",
                                                                                                        "Sixths - 5/6 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "1",
                                                                                                        "Twelfths - 1/12 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "5",
                                                                                                        "Twelfths - 5/12 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "7",
                                                                                                        "Twelfths - 7/12 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "11",
                                                                                                        "Twelfths - 11/12 column",
                                                                                                    ),
                                                                                                ],
                                                                                                label="Column size",
                                                                                                required=False,
                                                                                            ),
                                                                                        )
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ],
                                                                        label="Content",
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "paragraph_block",
                                                        wagtail.blocks.RichTextBlock(
                                                            icon="pilcrow"
                                                        ),
                                                    ),
                                                    (
                                                        "image_block",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "attribution",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "block_quote",
                                                        wagtail.blocks.BlockQuoteBlock(),
                                                    ),
                                                    (
                                                        "embed_block",
                                                        wagtail.embeds.blocks.EmbedBlock(
                                                            help_text="core.blocks.help_text_embed_block"
                                                        ),
                                                    ),
                                                    (
                                                        "button_block",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        help_text="page to link to",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.blocks.URLBlock(
                                                                        help_text="external URL to link to",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="the text on the button",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "style",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-primary",
                                                                                "Primary",
                                                                            ),
                                                                            (
                                                                                "btn-secondary",
                                                                                "Secondary",
                                                                            ),
                                                                            (
                                                                                "btn-success",
                                                                                "Success",
                                                                            ),
                                                                            (
                                                                                "btn-danger",
                                                                                "Danger",
                                                                            ),
                                                                            (
                                                                                "btn-info",
                                                                                "Info",
                                                                            ),
                                                                            (
                                                                                "btn-light",
                                                                                "Light",
                                                                            ),
                                                                            (
                                                                                "btn-dark",
                                                                                "Dark",
                                                                            ),
                                                                            (
                                                                                "btn-outline-primary",
                                                                                "Outline Primary",
                                                                            ),
                                                                            (
                                                                                "btn-outline-secondary",
                                                                                "Outline Secondary",
                                                                            ),
                                                                            (
                                                                                "btn-outline-success",
                                                                                "Outline Success",
                                                                            ),
                                                                            (
                                                                                "btn-outline-danger",
                                                                                "Outline Danger",
                                                                            ),
                                                                            (
                                                                                "btn-outline-info",
                                                                                "Outline Info",
                                                                            ),
                                                                            (
                                                                                "btn-outline-light",
                                                                                "Outline Light",
                                                                            ),
                                                                            (
                                                                                "btn-outline-dark",
                                                                                "Outline Dark",
                                                                            ),
                                                                        ],
                                                                        label="Button style",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "size",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-sm",
                                                                                "Small",
                                                                            ),
                                                                            (
                                                                                "",
                                                                                "Default",
                                                                            ),
                                                                            (
                                                                                "btn-lg",
                                                                                "Large",
                                                                            ),
                                                                        ],
                                                                        label="Button size",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ],
                                                use_json_field=True,
                                            ),
                                        ),
                                    ],
                                    icon="image",
                                    template="blocks/hero_block.html",
                                    verbose_name="Hero Block",
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="Seiten Inhalt",
                    ),
                ),
                (
                    "introduction_headline",
                    models.CharField(max_length=255, verbose_name="Headline"),
                ),
                (
                    "introduction_subheadline",
                    models.CharField(max_length=255, verbose_name="Sub-Headline"),
                ),
                (
                    "introduction_text",
                    models.TextField(
                        blank=True,
                        help_text="Text unter der Headline",
                        null=True,
                        verbose_name="Eingangstext",
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Header Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
