# Generated by Django 4.1.13 on 2023-11-13 12:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0015_alter_solutionapplicationindexpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutionapplicationindexpage",
            name="introduction_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text unter der Headline",
                null=True,
                verbose_name="Eingangstext",
            ),
        ),
        migrations.AlterField(
            model_name="solutionapplicationpage",
            name="introduction_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text unter der Headline",
                null=True,
                verbose_name="Eingangstext",
            ),
        ),
        migrations.AlterField(
            model_name="solutionindexpage",
            name="introduction_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text unter der Headline",
                null=True,
                verbose_name="Eingangstext",
            ),
        ),
        migrations.AlterField(
            model_name="solutionpage",
            name="introduction_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text unter der Headline",
                null=True,
                verbose_name="Eingangstext",
            ),
        ),
    ]
