# Generated by Django 4.1.13 on 2023-11-21 14:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("solutions", "0019_alter_solutionapplicationindexpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "row",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default"),
                                            ("text-bg-dark", "Schwarz"),
                                            ("text-bg-primary", "Rot"),
                                            ("text-bg-light", "Hellgrau"),
                                        ],
                                        label="Hintergrundfarbe",
                                        required=False,
                                    ),
                                ),
                                (
                                    "row_width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("12", "Voll"), ("10", "Zentriert")],
                                        label="Zeilenbreite",
                                        required=False,
                                    ),
                                ),
                                (
                                    "column_size",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (6, "Halb - 1/2 | 1/2 Spalten"),
                                            (4, "Drittel - 1/3 | 2/3 Spalten"),
                                            (8, "Drittel - 2/3 | 1/3 Spalten"),
                                        ],
                                        label="Spaltenaufteilung",
                                    ),
                                ),
                                (
                                    "mobile_ordering",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("first", "Erste über zweiter Spalte"),
                                            ("second", "Zweite über erster Spalte"),
                                        ],
                                        help_text="Welche Spalte in der Mobilen Ansicht zuerst zu sehen sein soll.",
                                        label="Mobile Anordnung",
                                    ),
                                ),
                                (
                                    "first",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "caption",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "attribution",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "shadow",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "shadow-none",
                                                                                    "None",
                                                                                ),
                                                                                (
                                                                                    "shadow-sm",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "shadow",
                                                                                    "Regular",
                                                                                ),
                                                                                (
                                                                                    "shadow-lg",
                                                                                    "Larger",
                                                                                ),
                                                                            ],
                                                                            label="Shadow",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Aspect Ratio",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "carousel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "images",
                                                                        wagtail.blocks.ListBlock(
                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                required=True
                                                                            )
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "pre_headline",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Pre-Headline",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "headline",
                                                                        wagtail.blocks.TextBlock(
                                                                            label="Headline",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            help_text="Inhalt",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            default="Mehr erfahren",
                                                                            help_text="Link Text, wird nur angezeigt wenn eine Seite oder ein",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "page",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            help_text="Seite auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="externe URL auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ],
                                                    label="Linker Block",
                                                ),
                                            )
                                        ],
                                        label="Linker Block",
                                        max_num=1,
                                        min_num=1,
                                    ),
                                ),
                                (
                                    "second",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "caption",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "attribution",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "shadow",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "shadow-none",
                                                                                    "None",
                                                                                ),
                                                                                (
                                                                                    "shadow-sm",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "shadow",
                                                                                    "Regular",
                                                                                ),
                                                                                (
                                                                                    "shadow-lg",
                                                                                    "Larger",
                                                                                ),
                                                                            ],
                                                                            label="Shadow",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Aspect Ratio",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "carousel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "images",
                                                                        wagtail.blocks.ListBlock(
                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                required=True
                                                                            )
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "pre_headline",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Pre-Headline",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "headline",
                                                                        wagtail.blocks.TextBlock(
                                                                            label="Headline",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            help_text="Inhalt",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            default="Mehr erfahren",
                                                                            help_text="Link Text, wird nur angezeigt wenn eine Seite oder ein",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "page",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            help_text="Seite auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="externe URL auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ],
                                                    label="Rechter Block",
                                                ),
                                            )
                                        ],
                                        label="Rechter Block",
                                        max_num=1,
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
