# Generated by Django 4.1.13 on 2024-04-12 14:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("puput", "0001_initial"),
        ("core", "0053_alter_dataprotectionpage_body_alter_homepage_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParatEntryPage",
            fields=[
                (
                    "entrypage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="puput.entrypage",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Subtitel"
                    ),
                ),
            ],
            options={
                "verbose_name": "PARAT Beitrag",
            },
            bases=("puput.entrypage", models.Model),
        ),
        migrations.CreateModel(
            name="ParatEntryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customdocument",
                    ),
                ),
                (
                    "parat_entry",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="news.paratentrypage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
