# Generated by Django 4.1.13 on 2024-04-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_dataprotectionpage_body_alter_homepage_body_and_more"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paratentrydocument",
            name="label",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Beschriftung"
            ),
        ),
        migrations.AlterField(
            model_name="paratentrydocument",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.customdocument",
                verbose_name="Dokument",
            ),
        ),
    ]
