# Generated by Django 4.1.13 on 2024-04-23 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("puput", "0001_initial"),
        ("news", "0002_paratentrydocument_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParatBlogPage",
            fields=[
                (
                    "blogpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="puput.blogpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parat Blog Page",
            },
            bases=("puput.blogpage",),
            managers=[
                ("extra", django.db.models.manager.Manager()),
            ],
        ),
    ]
