# Generated by Django 4.1.13 on 2024-05-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_paratblogpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paratentrypage",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Subtitel"
            ),
        ),
    ]
