# Generated by Django 4.1.13 on 2024-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_paratentrypage_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="paratblogpage",
            name="introduction_subheadline",
            field=models.CharField(
                default="Immer Aktuell", max_length=255, verbose_name="Headline"
            ),
        ),
    ]
