# Generated by Django 4.1.13 on 2024-05-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("news", "0005_paratblogpage_introduction_subheadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="paratblogpage",
            name="card_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Card Image",
            ),
        ),
    ]
