# Generated by Django 4.1.13 on 2023-11-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0006_alter_contactpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="dsgvo",
            field=models.BooleanField(verbose_name="DSGVO"),
        ),
    ]
