# Generated by Django 4.1.12 on 2023-10-30 10:28

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(max_length=255, unique=True, verbose_name="Label"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Expo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_to", django.contrib.postgres.fields.ranges.DateRangeField()),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="Titel"),
                ),
                ("city", models.CharField(max_length=255, verbose_name="Stadt")),
                (
                    "venue_location",
                    models.CharField(max_length=255, verbose_name="Standort am Venue"),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "categories",
                    models.ManyToManyField(
                        to="expo.expocategory", verbose_name="Kategorien"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
