# Generated by Django 4.1.12 on 2023-10-30 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expo",
            name="from_to",
        ),
        migrations.AddField(
            model_name="expo",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 30, 11, 54, 16, 286572, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Enddatum",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expo",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 30, 11, 54, 34, 889692, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Startdatum",
            ),
            preserve_default=False,
        ),
    ]
