# Generated by Django 4.1.13 on 2023-11-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_standardpage_body"),
        ("expo", "0002_remove_expo_from_to_expo_end_date_expo_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.customdocument"
            ),
        ),
    ]
