# Generated by Django 4.1.13 on 2023-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expo", "0014_alter_expopage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="expo",
            name="url_label",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="URL Label"
            ),
        ),
    ]
