# Generated by Django 4.1.13 on 2023-12-01 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expo", "0017_alter_expopage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expo",
            options={"ordering": ["-start_date"]},
        ),
    ]
