# Generated by Django 4.1.13 on 2023-12-04 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expo", "0018_alter_expo_options"),
        ("expo", "0018_expopage_canonical_url_expopage_og_image_and_more"),
    ]

    operations = []
