# Generated by Django 4.1.13 on 2024-02-15 10:46

from django.db import migrations, models
import parat.core.blocks.content_blocks
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("expo", "0019_merge_20231204_0832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expopage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "split_row_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default"),
                                            ("text-bg-dark", "Schwarz"),
                                            ("text-bg-primary", "Rot"),
                                            ("text-bg-light", "Hellgrau"),
                                        ],
                                        label="Hintergrundfarbe",
                                        required=False,
                                    ),
                                ),
                                (
                                    "column_size",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (6, "Halb - 1/2 | 1/2 Spalten"),
                                            (4, "Drittel - 1/3 | 2/3 Spalten"),
                                            (8, "Drittel - 2/3 | 1/3 Spalten"),
                                        ],
                                        label="Spaltenaufteilung",
                                    ),
                                ),
                                (
                                    "mobile_ordering",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("first", "Erste über zweiter Spalte"),
                                            ("second", "Zweite über erster Spalte"),
                                        ],
                                        help_text="Welche Spalte in der Mobilen Ansicht zuerst zu sehen sein soll.",
                                        label="Mobile Anordnung",
                                    ),
                                ),
                                (
                                    "first",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "caption",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "attribution",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "shadow",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "shadow-none",
                                                                                    "None",
                                                                                ),
                                                                                (
                                                                                    "shadow-sm",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "shadow",
                                                                                    "Regular",
                                                                                ),
                                                                                (
                                                                                    "shadow-lg",
                                                                                    "Larger",
                                                                                ),
                                                                            ],
                                                                            label="Shadow",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Bildformat",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "carousel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "images",
                                                                        wagtail.blocks.ListBlock(
                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                required=True
                                                                            )
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "pre_headline",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Pre-Headline",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "headline",
                                                                        wagtail.blocks.TextBlock(
                                                                            label="Headline",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            help_text="Inhalt",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            default="Mehr erfahren",
                                                                            help_text="Link Text, wird nur angezeigt wenn eine Seite oder ein",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "page",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            help_text="Seite auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="externe URL auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text_alignment",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "left",
                                                                                    "Linksbündig",
                                                                                ),
                                                                                (
                                                                                    "center",
                                                                                    "Zentriert",
                                                                                ),
                                                                            ],
                                                                            help_text="Textbündigkeit von Pre-Headline, Headline und Inhalt",
                                                                            label="Textbündigkeit",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "video_embed_block",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Vorschaubild",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Bildformat",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="Youtube oder Vimeo URL.",
                                                                            label="Video URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "local_video",
                                                                        parat.core.blocks.content_blocks.VideoChooserBlock(
                                                                            help_text="Lokal gehostetes Video aussuchen",
                                                                            label="Lokales Video",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "full_width",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False,
                                                                            label="Ganze Breite",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "auto_play",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=True,
                                                                            help_text="Bestimmt ob das Video automatisch abgespielt werden soll.",
                                                                            label="Auto Play",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ],
                                                    label="Linker Block",
                                                ),
                                            )
                                        ],
                                        label="Linker Block",
                                        max_num=1,
                                        min_num=1,
                                    ),
                                ),
                                (
                                    "second",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "caption",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "attribution",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "shadow",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "shadow-none",
                                                                                    "None",
                                                                                ),
                                                                                (
                                                                                    "shadow-sm",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "shadow",
                                                                                    "Regular",
                                                                                ),
                                                                                (
                                                                                    "shadow-lg",
                                                                                    "Larger",
                                                                                ),
                                                                            ],
                                                                            label="Shadow",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Bildformat",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "carousel",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "images",
                                                                        wagtail.blocks.ListBlock(
                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                required=True
                                                                            )
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "pre_headline",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Pre-Headline",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "headline",
                                                                        wagtail.blocks.TextBlock(
                                                                            label="Headline",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            help_text="Inhalt",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            default="Mehr erfahren",
                                                                            help_text="Link Text, wird nur angezeigt wenn eine Seite oder ein",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "page",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            help_text="Seite auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="externe URL auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text_alignment",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "left",
                                                                                    "Linksbündig",
                                                                                ),
                                                                                (
                                                                                    "center",
                                                                                    "Zentriert",
                                                                                ),
                                                                            ],
                                                                            help_text="Textbündigkeit von Pre-Headline, Headline und Inhalt",
                                                                            label="Textbündigkeit",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "video_embed_block",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Vorschaubild",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Bildformat",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="Youtube oder Vimeo URL.",
                                                                            label="Video URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "local_video",
                                                                        parat.core.blocks.content_blocks.VideoChooserBlock(
                                                                            help_text="Lokal gehostetes Video aussuchen",
                                                                            label="Lokales Video",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "full_width",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False,
                                                                            label="Ganze Breite",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "auto_play",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=True,
                                                                            help_text="Bestimmt ob das Video automatisch abgespielt werden soll.",
                                                                            label="Auto Play",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ],
                                                    label="Rechter Block",
                                                ),
                                            )
                                        ],
                                        label="Rechter Block",
                                        max_num=1,
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "full_row_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Default"),
                                            ("text-bg-dark", "Schwarz"),
                                            ("text-bg-primary", "Rot"),
                                            ("text-bg-light", "Hellgrau"),
                                        ],
                                        label="Hintergrundfarbe",
                                        required=False,
                                    ),
                                ),
                                (
                                    "first",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "caption",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "attribution",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "shadow",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "shadow-none",
                                                                                    "None",
                                                                                ),
                                                                                (
                                                                                    "shadow-sm",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "shadow",
                                                                                    "Regular",
                                                                                ),
                                                                                (
                                                                                    "shadow-lg",
                                                                                    "Larger",
                                                                                ),
                                                                            ],
                                                                            label="Shadow",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Bildformat",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "pre_headline",
                                                                        wagtail.blocks.CharBlock(
                                                                            label="Pre-Headline",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "headline",
                                                                        wagtail.blocks.TextBlock(
                                                                            label="Headline",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            help_text="Inhalt",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            default="Mehr erfahren",
                                                                            help_text="Link Text, wird nur angezeigt wenn eine Seite oder ein",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "page",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            help_text="Seite auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="externe URL auf die verlinkt werden soll",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "text_alignment",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "left",
                                                                                    "Linksbündig",
                                                                                ),
                                                                                (
                                                                                    "center",
                                                                                    "Zentriert",
                                                                                ),
                                                                            ],
                                                                            help_text="Textbündigkeit von Pre-Headline, Headline und Inhalt",
                                                                            label="Textbündigkeit",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "video_embed_block",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Vorschaubild",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "aspect_ratio",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "1-1",
                                                                                    "1:1",
                                                                                ),
                                                                                (
                                                                                    "3-2",
                                                                                    "3:2",
                                                                                ),
                                                                            ],
                                                                            label="Bildformat",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="Youtube oder Vimeo URL.",
                                                                            label="Video URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "local_video",
                                                                        parat.core.blocks.content_blocks.VideoChooserBlock(
                                                                            help_text="Lokal gehostetes Video aussuchen",
                                                                            label="Lokales Video",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "full_width",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=False,
                                                                            label="Ganze Breite",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "auto_play",
                                                                        wagtail.blocks.BooleanBlock(
                                                                            default=True,
                                                                            help_text="Bestimmt ob das Video automatisch abgespielt werden soll.",
                                                                            label="Auto Play",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ],
                                                    label="Block",
                                                ),
                                            )
                                        ],
                                        label="Block",
                                        max_num=1,
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("paragraph_block", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    (
                        "headline_and_text_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "pre_headline",
                                    wagtail.blocks.CharBlock(
                                        label="Pre-Headline", required=True
                                    ),
                                ),
                                (
                                    "headline",
                                    wagtail.blocks.CharBlock(
                                        label="Headline", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Inhalt", required=True
                                    ),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        default="Mehr erfahren",
                                        help_text="Link Text, wird nur angezeigt wenn eine Seite oder ein",
                                        required=True,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        help_text="Seite auf die verlinkt werden soll",
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="externe URL auf die verlinkt werden soll",
                                        required=False,
                                    ),
                                ),
                                (
                                    "centered",
                                    wagtail.blocks.BooleanBlock(
                                        label="Zentrierter Text", required=False
                                    ),
                                ),
                                (
                                    "link_with_button",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Link wird als Button dargestellt.",
                                        label="Buttonlink",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "shadow",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("shadow-none", "None"),
                                            ("shadow-sm", "Small"),
                                            ("shadow", "Regular"),
                                            ("shadow-lg", "Larger"),
                                        ],
                                        label="Shadow",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("block_quote", wagtail.blocks.BlockQuoteBlock()),
                    (
                        "embed_block",
                        wagtail.embeds.blocks.EmbedBlock(
                            help_text="core.blocks.help_text_embed_block"
                        ),
                    ),
                    (
                        "button_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        help_text="page to link to", required=False
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="external URL to link to",
                                        required=False,
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help_text="the text on the button",
                                        required=True,
                                    ),
                                ),
                                (
                                    "style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("btn-primary", "Primary"),
                                            ("btn-secondary", "Secondary"),
                                            ("btn-success", "Success"),
                                            ("btn-danger", "Danger"),
                                            ("btn-info", "Info"),
                                            ("btn-light", "Light"),
                                            ("btn-dark", "Dark"),
                                            ("btn-outline-primary", "Outline Primary"),
                                            (
                                                "btn-outline-secondary",
                                                "Outline Secondary",
                                            ),
                                            ("btn-outline-success", "Outline Success"),
                                            ("btn-outline-danger", "Outline Danger"),
                                            ("btn-outline-info", "Outline Info"),
                                            ("btn-outline-light", "Outline Light"),
                                            ("btn-outline-dark", "Outline Dark"),
                                        ],
                                        label="Button style",
                                        required=False,
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("btn-sm", "Small"),
                                            ("", "Default"),
                                            ("btn-lg", "Large"),
                                        ],
                                        label="Button size",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video_embed_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Vorschaubild", required=True
                                    ),
                                ),
                                (
                                    "aspect_ratio",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("1-1", "1:1"), ("3-2", "3:2")],
                                        label="Bildformat",
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="Youtube oder Vimeo URL.",
                                        label="Video URL",
                                        required=False,
                                    ),
                                ),
                                (
                                    "local_video",
                                    parat.core.blocks.content_blocks.VideoChooserBlock(
                                        help_text="Lokal gehostetes Video aussuchen",
                                        label="Lokales Video",
                                        required=False,
                                    ),
                                ),
                                (
                                    "full_width",
                                    wagtail.blocks.BooleanBlock(
                                        default=False,
                                        label="Ganze Breite",
                                        required=False,
                                    ),
                                ),
                                (
                                    "auto_play",
                                    wagtail.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Bestimmt ob das Video automatisch abgespielt werden soll.",
                                        label="Auto Play",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "foreground_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "pre_headline",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                ("headline", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="Inhalt", required=False
                                    ),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        default="Mehr erfahren",
                                        help_text="Link Text, wird nur angezeigt wenn eine Seite oder ein",
                                        required=True,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(
                                        help_text="Seite auf die verlinkt werden soll",
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.URLBlock(
                                        help_text="externe URL auf die verlinkt werden soll",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Seiten Inhalt",
            ),
        ),
        migrations.AlterField(
            model_name="expopage",
            name="introduction_headline",
            field=models.CharField(max_length=255, verbose_name="Pre-Headline"),
        ),
        migrations.AlterField(
            model_name="expopage",
            name="introduction_subheadline",
            field=models.CharField(max_length=255, verbose_name="Headline"),
        ),
    ]
