# Generated by Django 4.1.12 on 2023-10-27 13:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(max_length=255, unique=True, verbose_name="Label"),
                ),
                ("ordering", models.SmallIntegerField(verbose_name="Ordering")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DownloadLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(max_length=32, unique=True, verbose_name="Label"),
                ),
                (
                    "short_label",
                    models.CharField(
                        help_text="z.B. DE",
                        max_length=3,
                        unique=True,
                        verbose_name="Short Label",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Beschreibung"),
                ),
                (
                    "download_group",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downloads",
                        to="downloads.downloadgroup",
                        verbose_name="Gruppe",
                    ),
                ),
                (
                    "download_languages",
                    models.ManyToManyField(
                        to="downloads.downloadlanguage", verbose_name="Sprachen"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
