# Generated by Django 4.1.12 on 2023-10-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_customdocument"),
        ("downloads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="downloadgroup",
            options={"ordering": ["ordering"]},
        ),
        migrations.AlterField(
            model_name="download",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.customdocument"
            ),
        ),
    ]
