# Generated by Django 4.1.12 on 2023-10-27 13:52

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0002_alter_downloadgroup_options_alter_download_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="download",
            name="download_group",
            field=modelcluster.fields.ParentalKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="downloads",
                to="downloads.downloadgroup",
                verbose_name="Gruppe",
            ),
            preserve_default=False,
        ),
    ]
