# Generated by Django 4.1.12 on 2023-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0003_alter_download_download_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadlanguage",
            name="short_label",
            field=models.CharField(
                help_text="z.B. DE",
                max_length=3,
                unique=True,
                verbose_name="Sprachkürzel",
            ),
        ),
    ]
