# Generated by Django 4.1.13 on 2023-11-03 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0006_alter_downloadlanguage_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadlanguage",
            old_name="short_label",
            new_name="alpha_2",
        ),
    ]
