# Generated by Django 4.1.13 on 2023-11-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0021_alter_downloadindexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="download",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Beschreibung"
            ),
        ),
    ]
