#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

python << END
import os
import sys
import time

import psycopg2
import dj_database_url

suggest_unrecoverable_after = 30
start = time.time()

url = os.environ.get("DJANGO_DATABASE_URL", None)
url = dj_database_url.parse(url)

while True:
    try:
        psycopg2.connect(
            dbname=url["NAME"],
            user=url["USER"],
            password=url["PASSWORD"],
            host=url["HOST"],
            port=url["PORT"]
        )
        break
    except psycopg2.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
