# Generated by Django 4.1.12 on 2023-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpage",
            name="text",
        ),
        migrations.AddField(
            model_name="jobpage",
            name="short_description",
            field=models.CharField(
                default="",
                help_text="Short Description for display in List",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
