# Generated by Django 4.1.12 on 2023-10-18 11:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("jobs", "0002_remove_jobpage_text_jobpage_short_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("heading", models.TextField(blank=True, help_text="Title")),
                ("subheading", models.TextField(blank=True, help_text="Subtitle")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "general",
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            "row_block",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "row_width",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ("12", "Full"),
                                                                ("10", "Centered"),
                                                            ],
                                                            label="Row size",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "content",
                                                        wagtail.blocks.StreamBlock(
                                                            [
                                                                (
                                                                    "Column",
                                                                    wagtail.blocks.StructBlock(
                                                                        [
                                                                            (
                                                                                "column_size",
                                                                                wagtail.blocks.ChoiceBlock(
                                                                                    choices=[
                                                                                        (
                                                                                            "",
                                                                                            "Auto",
                                                                                        ),
                                                                                        (
                                                                                            "12",
                                                                                            "Full row",
                                                                                        ),
                                                                                        (
                                                                                            "6",
                                                                                            "Half - 1/2 column",
                                                                                        ),
                                                                                        (
                                                                                            "4",
                                                                                            "Thirds - 1/3 column",
                                                                                        ),
                                                                                        (
                                                                                            "8",
                                                                                            "Thirds - 2/3 column",
                                                                                        ),
                                                                                        (
                                                                                            "3",
                                                                                            "Quarters - 1/4 column",
                                                                                        ),
                                                                                        (
                                                                                            "9",
                                                                                            "Quarters - 3/4 column",
                                                                                        ),
                                                                                        (
                                                                                            "2",
                                                                                            "Sixths - 1/6 column",
                                                                                        ),
                                                                                        (
                                                                                            "10",
                                                                                            "Sixths - 5/6 column",
                                                                                        ),
                                                                                        (
                                                                                            "1",
                                                                                            "Twelfths - 1/12 column",
                                                                                        ),
                                                                                        (
                                                                                            "5",
                                                                                            "Twelfths - 5/12 column",
                                                                                        ),
                                                                                        (
                                                                                            "7",
                                                                                            "Twelfths - 7/12 column",
                                                                                        ),
                                                                                        (
                                                                                            "11",
                                                                                            "Twelfths - 11/12 column",
                                                                                        ),
                                                                                    ],
                                                                                    label="Column size",
                                                                                    required=False,
                                                                                ),
                                                                            ),
                                                                            (
                                                                                "content",
                                                                                wagtail.blocks.StreamBlock(
                                                                                    [
                                                                                        (
                                                                                            "ColumnHeroImage",
                                                                                            wagtail.blocks.StructBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "image",
                                                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                                                            required=True
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "caption",
                                                                                                        wagtail.blocks.CharBlock(
                                                                                                            required=False
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "attribution",
                                                                                                        wagtail.blocks.CharBlock(
                                                                                                            required=False
                                                                                                        ),
                                                                                                    ),
                                                                                                ]
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "ColumnHeroText",
                                                                                            wagtail.blocks.StructBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "pre_headline",
                                                                                                        wagtail.blocks.CharBlock(
                                                                                                            help_text="The pre-title",
                                                                                                            required=True,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "headline",
                                                                                                        wagtail.blocks.CharBlock(
                                                                                                            help_text="The Title",
                                                                                                            required=True,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "text",
                                                                                                        wagtail.blocks.RichTextBlock(
                                                                                                            help_text="Content Block",
                                                                                                            required=True,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "link_text",
                                                                                                        wagtail.blocks.CharBlock(
                                                                                                            default="Read more",
                                                                                                            help_text="Link Text",
                                                                                                            required=True,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "page",
                                                                                                        wagtail.blocks.PageChooserBlock(
                                                                                                            help_text="page to link to",
                                                                                                            required=True,
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "url",
                                                                                                        wagtail.blocks.URLBlock(
                                                                                                            help_text="external URL to link to",
                                                                                                            required=False,
                                                                                                        ),
                                                                                                    ),
                                                                                                ]
                                                                                            ),
                                                                                        ),
                                                                                    ],
                                                                                    label="Content",
                                                                                ),
                                                                            ),
                                                                        ]
                                                                    ),
                                                                )
                                                            ],
                                                            label="Content",
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "paragraph_block",
                                            wagtail.blocks.RichTextBlock(
                                                icon="pilcrow"
                                            ),
                                        ),
                                        (
                                            "image_block",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "image",
                                                        wagtail.images.blocks.ImageChooserBlock(
                                                            required=True
                                                        ),
                                                    ),
                                                    (
                                                        "caption",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                    (
                                                        "attribution",
                                                        wagtail.blocks.CharBlock(
                                                            required=False
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "block_quote",
                                            wagtail.blocks.BlockQuoteBlock(),
                                        ),
                                        (
                                            "button_block",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "page",
                                                        wagtail.blocks.PageChooserBlock(
                                                            help_text="page to link to",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "url",
                                                        wagtail.blocks.URLBlock(
                                                            help_text="external URL to link to",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "text",
                                                        wagtail.blocks.CharBlock(
                                                            help_text="the text on the button",
                                                            required=True,
                                                        ),
                                                    ),
                                                    (
                                                        "style",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                (
                                                                    "btn-primary",
                                                                    "Primary",
                                                                ),
                                                                (
                                                                    "btn-secondary",
                                                                    "Secondary",
                                                                ),
                                                                (
                                                                    "btn-success",
                                                                    "Success",
                                                                ),
                                                                (
                                                                    "btn-danger",
                                                                    "Danger",
                                                                ),
                                                                ("btn-info", "Info"),
                                                                ("btn-light", "Light"),
                                                                ("btn-dark", "Dark"),
                                                                (
                                                                    "btn-outline-primary",
                                                                    "Outline Primary",
                                                                ),
                                                                (
                                                                    "btn-outline-secondary",
                                                                    "Outline Secondary",
                                                                ),
                                                                (
                                                                    "btn-outline-success",
                                                                    "Outline Success",
                                                                ),
                                                                (
                                                                    "btn-outline-danger",
                                                                    "Outline Danger",
                                                                ),
                                                                (
                                                                    "btn-outline-info",
                                                                    "Outline Info",
                                                                ),
                                                                (
                                                                    "btn-outline-light",
                                                                    "Outline Light",
                                                                ),
                                                                (
                                                                    "btn-outline-dark",
                                                                    "Outline Dark",
                                                                ),
                                                            ],
                                                            label="Button style",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "size",
                                                        wagtail.blocks.ChoiceBlock(
                                                            choices=[
                                                                ("btn-sm", "Small"),
                                                                ("", "Default"),
                                                                ("btn-lg", "Large"),
                                                            ],
                                                            label="Button size",
                                                            required=False,
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "foreground_color",
                                            wagtail.blocks.CharBlock(required=False),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "row_block",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "row_width",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "12",
                                                                                "Full",
                                                                            ),
                                                                            (
                                                                                "10",
                                                                                "Centered",
                                                                            ),
                                                                        ],
                                                                        label="Row size",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "content",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "Column",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "column_size",
                                                                                            wagtail.blocks.ChoiceBlock(
                                                                                                choices=[
                                                                                                    (
                                                                                                        "",
                                                                                                        "Auto",
                                                                                                    ),
                                                                                                    (
                                                                                                        "12",
                                                                                                        "Full row",
                                                                                                    ),
                                                                                                    (
                                                                                                        "6",
                                                                                                        "Half - 1/2 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "4",
                                                                                                        "Thirds - 1/3 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "8",
                                                                                                        "Thirds - 2/3 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "3",
                                                                                                        "Quarters - 1/4 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "9",
                                                                                                        "Quarters - 3/4 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "2",
                                                                                                        "Sixths - 1/6 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "10",
                                                                                                        "Sixths - 5/6 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "1",
                                                                                                        "Twelfths - 1/12 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "5",
                                                                                                        "Twelfths - 5/12 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "7",
                                                                                                        "Twelfths - 7/12 column",
                                                                                                    ),
                                                                                                    (
                                                                                                        "11",
                                                                                                        "Twelfths - 11/12 column",
                                                                                                    ),
                                                                                                ],
                                                                                                label="Column size",
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "content",
                                                                                            wagtail.blocks.StreamBlock(
                                                                                                [
                                                                                                    (
                                                                                                        "ColumnHeroImage",
                                                                                                        wagtail.blocks.StructBlock(
                                                                                                            [
                                                                                                                (
                                                                                                                    "image",
                                                                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                                                                        required=True
                                                                                                                    ),
                                                                                                                ),
                                                                                                                (
                                                                                                                    "caption",
                                                                                                                    wagtail.blocks.CharBlock(
                                                                                                                        required=False
                                                                                                                    ),
                                                                                                                ),
                                                                                                                (
                                                                                                                    "attribution",
                                                                                                                    wagtail.blocks.CharBlock(
                                                                                                                        required=False
                                                                                                                    ),
                                                                                                                ),
                                                                                                            ]
                                                                                                        ),
                                                                                                    ),
                                                                                                    (
                                                                                                        "ColumnHeroText",
                                                                                                        wagtail.blocks.StructBlock(
                                                                                                            [
                                                                                                                (
                                                                                                                    "pre_headline",
                                                                                                                    wagtail.blocks.CharBlock(
                                                                                                                        help_text="The pre-title",
                                                                                                                        required=True,
                                                                                                                    ),
                                                                                                                ),
                                                                                                                (
                                                                                                                    "headline",
                                                                                                                    wagtail.blocks.CharBlock(
                                                                                                                        help_text="The Title",
                                                                                                                        required=True,
                                                                                                                    ),
                                                                                                                ),
                                                                                                                (
                                                                                                                    "text",
                                                                                                                    wagtail.blocks.RichTextBlock(
                                                                                                                        help_text="Content Block",
                                                                                                                        required=True,
                                                                                                                    ),
                                                                                                                ),
                                                                                                                (
                                                                                                                    "link_text",
                                                                                                                    wagtail.blocks.CharBlock(
                                                                                                                        default="Read more",
                                                                                                                        help_text="Link Text",
                                                                                                                        required=True,
                                                                                                                    ),
                                                                                                                ),
                                                                                                                (
                                                                                                                    "page",
                                                                                                                    wagtail.blocks.PageChooserBlock(
                                                                                                                        help_text="page to link to",
                                                                                                                        required=True,
                                                                                                                    ),
                                                                                                                ),
                                                                                                                (
                                                                                                                    "url",
                                                                                                                    wagtail.blocks.URLBlock(
                                                                                                                        help_text="external URL to link to",
                                                                                                                        required=False,
                                                                                                                    ),
                                                                                                                ),
                                                                                                            ]
                                                                                                        ),
                                                                                                    ),
                                                                                                ],
                                                                                                label="Content",
                                                                                            ),
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ],
                                                                        label="Content",
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "paragraph_block",
                                                        wagtail.blocks.RichTextBlock(
                                                            icon="pilcrow"
                                                        ),
                                                    ),
                                                    (
                                                        "image_block",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "image",
                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                        required=True
                                                                    ),
                                                                ),
                                                                (
                                                                    "caption",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                                (
                                                                    "attribution",
                                                                    wagtail.blocks.CharBlock(
                                                                        required=False
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "block_quote",
                                                        wagtail.blocks.BlockQuoteBlock(),
                                                    ),
                                                    (
                                                        "button_block",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        help_text="page to link to",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.blocks.URLBlock(
                                                                        help_text="external URL to link to",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "text",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="the text on the button",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "style",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-primary",
                                                                                "Primary",
                                                                            ),
                                                                            (
                                                                                "btn-secondary",
                                                                                "Secondary",
                                                                            ),
                                                                            (
                                                                                "btn-success",
                                                                                "Success",
                                                                            ),
                                                                            (
                                                                                "btn-danger",
                                                                                "Danger",
                                                                            ),
                                                                            (
                                                                                "btn-info",
                                                                                "Info",
                                                                            ),
                                                                            (
                                                                                "btn-light",
                                                                                "Light",
                                                                            ),
                                                                            (
                                                                                "btn-dark",
                                                                                "Dark",
                                                                            ),
                                                                            (
                                                                                "btn-outline-primary",
                                                                                "Outline Primary",
                                                                            ),
                                                                            (
                                                                                "btn-outline-secondary",
                                                                                "Outline Secondary",
                                                                            ),
                                                                            (
                                                                                "btn-outline-success",
                                                                                "Outline Success",
                                                                            ),
                                                                            (
                                                                                "btn-outline-danger",
                                                                                "Outline Danger",
                                                                            ),
                                                                            (
                                                                                "btn-outline-info",
                                                                                "Outline Info",
                                                                            ),
                                                                            (
                                                                                "btn-outline-light",
                                                                                "Outline Light",
                                                                            ),
                                                                            (
                                                                                "btn-outline-dark",
                                                                                "Outline Dark",
                                                                            ),
                                                                        ],
                                                                        label="Button style",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "size",
                                                                    wagtail.blocks.ChoiceBlock(
                                                                        choices=[
                                                                            (
                                                                                "btn-sm",
                                                                                "Small",
                                                                            ),
                                                                            (
                                                                                "",
                                                                                "Default",
                                                                            ),
                                                                            (
                                                                                "btn-lg",
                                                                                "Large",
                                                                            ),
                                                                        ],
                                                                        label="Button size",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                        use_json_field=True,
                        verbose_name="core.models.standardpage_verbose_name_body",
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Header Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
