# Generated by Django 4.1.12 on 2023-11-02 21:01

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_remove_jobindexpage_introduction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "general",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "paragraph_block",
                                    wagtail.blocks.RichTextBlock(icon="pilcrow"),
                                ),
                                (
                                    "image_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "attribution",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("block_quote", wagtail.blocks.BlockQuoteBlock()),
                                (
                                    "embed_block",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="core.blocks.help_text_embed_block"
                                    ),
                                ),
                                (
                                    "button_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    help_text="page to link to",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    help_text="external URL to link to",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    help_text="the text on the button",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "style",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-primary", "Primary"),
                                                        ("btn-secondary", "Secondary"),
                                                        ("btn-success", "Success"),
                                                        ("btn-danger", "Danger"),
                                                        ("btn-info", "Info"),
                                                        ("btn-light", "Light"),
                                                        ("btn-dark", "Dark"),
                                                        (
                                                            "btn-outline-primary",
                                                            "Outline Primary",
                                                        ),
                                                        (
                                                            "btn-outline-secondary",
                                                            "Outline Secondary",
                                                        ),
                                                        (
                                                            "btn-outline-success",
                                                            "Outline Success",
                                                        ),
                                                        (
                                                            "btn-outline-danger",
                                                            "Outline Danger",
                                                        ),
                                                        (
                                                            "btn-outline-info",
                                                            "Outline Info",
                                                        ),
                                                        (
                                                            "btn-outline-light",
                                                            "Outline Light",
                                                        ),
                                                        (
                                                            "btn-outline-dark",
                                                            "Outline Dark",
                                                        ),
                                                    ],
                                                    label="Button style",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "size",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-sm", "Small"),
                                                        ("", "Default"),
                                                        ("btn-lg", "Large"),
                                                    ],
                                                    label="Button size",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "job_list_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    max_length=255
                                                ),
                                            ),
                                            (
                                                "link_text",
                                                wagtail.blocks.CharBlock(
                                                    default="See More", max_length=255
                                                ),
                                            ),
                                            (
                                                "content",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "Job",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "job",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            page_type=[
                                                                                "jobs.JobPage"
                                                                            ]
                                                                        ),
                                                                    )
                                                                ]
                                                            ),
                                                        )
                                                    ],
                                                    label="Content",
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "dynamic_job_list_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    max_length=255
                                                ),
                                            ),
                                            (
                                                "link_text",
                                                wagtail.blocks.CharBlock(
                                                    default="See More", max_length=255
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ],
                            use_json_field=True,
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "foreground_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "paragraph_block",
                                                wagtail.blocks.RichTextBlock(
                                                    icon="pilcrow"
                                                ),
                                            ),
                                            (
                                                "image_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "attribution",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "block_quote",
                                                wagtail.blocks.BlockQuoteBlock(),
                                            ),
                                            (
                                                "embed_block",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    help_text="core.blocks.help_text_embed_block"
                                                ),
                                            ),
                                            (
                                                "button_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="page to link to",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="external URL to link to",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="the text on the button",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "style",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-primary",
                                                                        "Primary",
                                                                    ),
                                                                    (
                                                                        "btn-secondary",
                                                                        "Secondary",
                                                                    ),
                                                                    (
                                                                        "btn-success",
                                                                        "Success",
                                                                    ),
                                                                    (
                                                                        "btn-danger",
                                                                        "Danger",
                                                                    ),
                                                                    (
                                                                        "btn-info",
                                                                        "Info",
                                                                    ),
                                                                    (
                                                                        "btn-light",
                                                                        "Light",
                                                                    ),
                                                                    (
                                                                        "btn-dark",
                                                                        "Dark",
                                                                    ),
                                                                    (
                                                                        "btn-outline-primary",
                                                                        "Outline Primary",
                                                                    ),
                                                                    (
                                                                        "btn-outline-secondary",
                                                                        "Outline Secondary",
                                                                    ),
                                                                    (
                                                                        "btn-outline-success",
                                                                        "Outline Success",
                                                                    ),
                                                                    (
                                                                        "btn-outline-danger",
                                                                        "Outline Danger",
                                                                    ),
                                                                    (
                                                                        "btn-outline-info",
                                                                        "Outline Info",
                                                                    ),
                                                                    (
                                                                        "btn-outline-light",
                                                                        "Outline Light",
                                                                    ),
                                                                    (
                                                                        "btn-outline-dark",
                                                                        "Outline Dark",
                                                                    ),
                                                                ],
                                                                label="Button style",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("btn-sm", "Small"),
                                                                    ("", "Default"),
                                                                    ("btn-lg", "Large"),
                                                                ],
                                                                label="Button size",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "job_list_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=255
                                                            ),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.blocks.CharBlock(
                                                                default="See More",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                        (
                                                            "content",
                                                            wagtail.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "Job",
                                                                        wagtail.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "job",
                                                                                    wagtail.blocks.PageChooserBlock(
                                                                                        page_type=[
                                                                                            "jobs.JobPage"
                                                                                        ]
                                                                                    ),
                                                                                )
                                                                            ]
                                                                        ),
                                                                    )
                                                                ],
                                                                label="Content",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "dynamic_job_list_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=255
                                                            ),
                                                        ),
                                                        (
                                                            "link_text",
                                                            wagtail.blocks.CharBlock(
                                                                default="See More",
                                                                max_length=255,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        use_json_field=True,
                                    ),
                                ),
                            ],
                            icon="image",
                            template="blocks/hero_block.html",
                            verbose_name="Hero Block",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Seiten Inhalt",
            ),
        ),
    ]
