# Generated by Django 4.1.13 on 2023-11-13 12:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0020_alter_jobindexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobindexpage",
            name="introduction_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text unter der Headline",
                null=True,
                verbose_name="Eingangstext",
            ),
        ),
    ]
