# Generated by Django 4.1.12 on 2023-10-09 13:34

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "general",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "paragraph_block",
                                    wagtail.blocks.RichTextBlock(icon="pilcrow"),
                                ),
                                (
                                    "image_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "attribution",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("block_quote", wagtail.blocks.BlockQuoteBlock()),
                                (
                                    "embed_block",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="core.blocks.help_text_embed_block"
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "foreground_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "paragraph_block",
                                                wagtail.blocks.RichTextBlock(
                                                    icon="pilcrow"
                                                ),
                                            ),
                                            (
                                                "image_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "attribution",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "block_quote",
                                                wagtail.blocks.BlockQuoteBlock(),
                                            ),
                                            (
                                                "embed_block",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    help_text="core.blocks.help_text_embed_block"
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="core.models.standardpage_verbose_name_body",
            ),
        ),
    ]
