# Generated by Django 4.1.12 on 2023-10-09 14:12

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "general",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "paragraph_block",
                                    wagtail.blocks.RichTextBlock(icon="pilcrow"),
                                ),
                                (
                                    "image_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                            (
                                                "caption",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "attribution",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("block_quote", wagtail.blocks.BlockQuoteBlock()),
                                (
                                    "button_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    help_text="page to link to",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "url",
                                                wagtail.blocks.URLBlock(
                                                    help_text="external URL to link to",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    help_text="the text on the button",
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "style",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-primary", "Primary"),
                                                        ("btn-secondary", "Secondary"),
                                                        ("btn-success", "Success"),
                                                        ("btn-danger", "Danger"),
                                                        ("btn-info", "Info"),
                                                        ("btn-light", "Light"),
                                                        ("btn-dark", "Dark"),
                                                        (
                                                            "btn-outline-primary",
                                                            "Primary",
                                                        ),
                                                        (
                                                            "btn-outline-secondary",
                                                            "Secondary",
                                                        ),
                                                        (
                                                            "btn-outline-success",
                                                            "Success",
                                                        ),
                                                        (
                                                            "btn-outline-danger",
                                                            "Danger",
                                                        ),
                                                        ("btn-outline-info", "Info"),
                                                        ("btn-outline-light", "Light"),
                                                        ("btn-outline-dark", "Dark"),
                                                    ],
                                                    label="Button style",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "size",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("btn-sm", "Small"),
                                                        ("", "Default"),
                                                        ("btn-lg", "Large"),
                                                    ],
                                                    label="Button size",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "background_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "foreground_color",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "paragraph_block",
                                                wagtail.blocks.RichTextBlock(
                                                    icon="pilcrow"
                                                ),
                                            ),
                                            (
                                                "image_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "caption",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "attribution",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "block_quote",
                                                wagtail.blocks.BlockQuoteBlock(),
                                            ),
                                            (
                                                "button_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="page to link to",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="external URL to link to",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="the text on the button",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "style",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "btn-primary",
                                                                        "Primary",
                                                                    ),
                                                                    (
                                                                        "btn-secondary",
                                                                        "Secondary",
                                                                    ),
                                                                    (
                                                                        "btn-success",
                                                                        "Success",
                                                                    ),
                                                                    (
                                                                        "btn-danger",
                                                                        "Danger",
                                                                    ),
                                                                    (
                                                                        "btn-info",
                                                                        "Info",
                                                                    ),
                                                                    (
                                                                        "btn-light",
                                                                        "Light",
                                                                    ),
                                                                    (
                                                                        "btn-dark",
                                                                        "Dark",
                                                                    ),
                                                                    (
                                                                        "btn-outline-primary",
                                                                        "Primary",
                                                                    ),
                                                                    (
                                                                        "btn-outline-secondary",
                                                                        "Secondary",
                                                                    ),
                                                                    (
                                                                        "btn-outline-success",
                                                                        "Success",
                                                                    ),
                                                                    (
                                                                        "btn-outline-danger",
                                                                        "Danger",
                                                                    ),
                                                                    (
                                                                        "btn-outline-info",
                                                                        "Info",
                                                                    ),
                                                                    (
                                                                        "btn-outline-light",
                                                                        "Light",
                                                                    ),
                                                                    (
                                                                        "btn-outline-dark",
                                                                        "Dark",
                                                                    ),
                                                                ],
                                                                label="Button style",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("btn-sm", "Small"),
                                                                    ("", "Default"),
                                                                    ("btn-lg", "Large"),
                                                                ],
                                                                label="Button size",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
                verbose_name="core.models.standardpage_verbose_name_body",
            ),
        ),
    ]
