# Generated by Django 4.1.11 on 2023-10-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("core", "0004_standardpage_header_image_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="header_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Titelbild",
            ),
        ),
    ]
