# Generated by Django 4.1.12 on 2023-10-13 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_standardpage_body_socialmediafooter"),
        ("core", "0006_alter_standardpage_header_image_homepage"),
    ]

    operations = []
