# Generated by Django 4.1.13 on 2023-11-03 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_customdocument"),
        ("core", "0017_alter_standardpage_body"),
    ]

    operations = []
