# Generated by Django 4.1.13 on 2023-12-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("core", "0038_homepage_canonical_url_homepage_og_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ga_g_tracking_id",
                    models.CharField(
                        blank=True,
                        help_text='Ihre Google Analytics 4 tracking ID (beginnt mit "G-")',
                        max_length=255,
                        verbose_name="G Tracking ID",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking",
            },
        ),
    ]
