# Generated by Django 4.1.13 on 2023-12-05 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_custommainmenu_custommainmenuitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custommainmenu",
            name="limit_from",
        ),
        migrations.RemoveField(
            model_name="custommainmenu",
            name="limit_to",
        ),
    ]
