# Generated by Django 4.1.13 on 2023-12-05 09:49

from django.db import migrations


def migrate_main_menu_data(apps, schema_editor):
    try:
        MainMenu = apps.get_model("wagtailmenus", "mainmenu")
        MainMenuItem = apps.get_model("wagtailmenus", "mainmenuitem")
        CustomMainMenu = apps.get_model("core", "CustomMainMenu")
        CustomMainMenuItem = apps.get_model("core", "CustomMainMenuItem")
        for mm in MainMenu.objects.all():
            cmm = CustomMainMenu()
            for field in mm._meta.fields:
                setattr(cmm, field.name, getattr(mm, field.name))
            cmm.save()
        for mmi in MainMenuItem.objects.all():
            cmmi = CustomMainMenuItem()
            for field in mmi._meta.fields:
                if field.name == "menu":
                    cmmi.menu_id = getattr(mmi, field.name).id
                else:
                    setattr(cmmi, field.name, getattr(mmi, field.name))
            cmmi.save()
    except LookupError:
        pass


def reverse_main_menu_data(apps, schema_editor):
    CustomMainMenu = apps.get_model("core", "CustomMainMenu")
    CustomMainMenuItem = apps.get_model("core", "CustomMainMenuItem")
    CustomMainMenuItem.objects.all().delete()
    CustomMainMenu.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_remove_custommainmenu_limit_from_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_main_menu_data, reverse_code=reverse_main_menu_data
        ),
    ]
