# Generated by Django 4.1.13 on 2023-12-13 12:49

from django.db import migrations


def migrate_flat_menu_data(apps, schema_editor):
    try:
        FlatMenu = apps.get_model("wagtailmenus", "FlatMenu")
        FlatMenuItem = apps.get_model("wagtailmenus", "FlatMenuItem")
        CustomFlatMenu = apps.get_model("core", "CustomFlatMenu")
        CustomFlatMenuItem = apps.get_model("core", "CustomFlatMenuItem")
        for fm in FlatMenu.objects.all():
            cfm = CustomFlatMenu()
            for field in fm._meta.fields:
                setattr(cfm, field.name, getattr(fm, field.name))
            cfm.save()
        for fmi in FlatMenuItem.objects.all():
            cfmi = CustomFlatMenuItem()
            for field in fmi._meta.fields:
                if field.name == "menu":
                    cfmi.menu_id = getattr(fmi, field.name).id
                else:
                    setattr(cfmi, field.name, getattr(fmi, field.name))
            cfmi.save()
    except LookupError:
        pass


def reverse_Flat_menu_data(apps, schema_editor):
    CustomFlatMenu = apps.get_model("core", "CustomFlatMenu")
    CustomFlatMenuItem = apps.get_model("core", "CustomFlatMenuItem")
    CustomFlatMenuItem.objects.all().delete()
    CustomFlatMenu.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_customflatmenu_customflatmenuitem"),
    ]

    operations = [
        migrations.RunPython(
            migrate_flat_menu_data, reverse_code=reverse_Flat_menu_data
        )
    ]
