# Generated by Django 4.1.13 on 2023-12-13 13:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("core", "0044_migrate_flat_menu_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customflatmenu",
            options={},
        ),
        migrations.AlterModelOptions(
            name="customflatmenuitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="customflatmenu",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="customflatmenu",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="customflatmenu",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customflatmenuitem",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="customflatmenuitem",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="customflatmenuitem",
            name="menu",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="core.customflatmenu",
            ),
        ),
    ]
