# Generated by Django 4.1.13 on 2023-12-13 13:52

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_alter_customflatmenu_options_and_more"),
    ]

    operations = [
        BootstrapTranslatableModel("core.CustomFlatMenu"),
        BootstrapTranslatableModel("core.CustomFlatMenuItem"),
    ]
