# Generated by Django 4.1.13 on 2024-01-09 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_customflatmenu_locale_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMediaFooter",
        ),
    ]
