# Generated by Django 4.1.13 on 2024-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_alter_dataprotectionpage_body_alter_homepage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommainmenuitem",
            name="link_open_new_tab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="custommainmenuitem",
            name="link_text_en",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="custommainmenuitem",
            name="link_url_en",
            field=models.URLField(blank=True),
        ),
    ]
