# Generated by Django 4.1.11 on 2023-09-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="author_name",
            field=models.TextField(default="Unknown", max_length=64),
        ),
    ]
