# Generated by Django 4.1.12 on 2023-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="author_name",
            field=models.TextField(default="Unknown"),
        ),
    ]
