# Generated by Django 4.1.13 on 2023-12-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("footer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footeritem",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="wagtailcore.page",
                verbose_name="Seite",
            ),
        ),
    ]
