# Generated by Django 4.1.13 on 2023-12-14 15:22

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0002_alter_footeritem_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footeritem",
            name="column",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="footer.footercolumn",
                verbose_name="Spalte",
            ),
        ),
    ]
