# Generated by Django 4.1.13 on 2023-12-14 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0003_alter_footeritem_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footeritem",
            options={"ordering": ["sort_order"]},
        ),
    ]
