# Generated by Django 4.1.13 on 2023-12-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0005_alter_footeritem_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="footercolumn",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
