# Generated by Django 4.1.13 on 2023-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0006_footercolumn_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footercolumn",
            options={"ordering": ["ordering", "title"]},
        ),
        migrations.RemoveField(
            model_name="footercolumn",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="footercolumn",
            name="ordering",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
