# Generated by Django 4.1.13 on 2024-01-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0008_alter_footeritem_page_footerbottomitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footerbottomitem",
            options={"ordering": ["ordering", "title"]},
        ),
        migrations.RemoveField(
            model_name="footerbottomitem",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="footerbottomitem",
            name="ordering",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
