# Generated by Django 4.1.13 on 2024-01-10 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0009_alter_footerbottomitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footerbottomitem",
            name="icon_name",
        ),
    ]
